language:
  ruby

rvm:
  - '2.4'
  - '2.5'
  - '2.6.2'
script:
  bundle exec rake
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base r-base-dev
  - sudo Rscript -e "install.packages(c('Rserve','icc','irr'),,'http://cran.us.r-project.org')"
